Task_1_1_3
rottenfishh/OOP pull request #13
Opened 2024-09-30 16:16 UTC by rottenfishh

2024-10-07 12:21 UTC, shadrina requested changes

2024-10-07 12:21 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Add.java
> +    final Expression right;
Видимость. Приучите себя всегда при любом объявлении поля о ней думать. О финальности раз, о видимости два.

2024-10-07 12:21 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Add.java
> +    public String convertToString() {
Чем `toString` не мил? И в отладчике тогда все будет красиво.

2024-10-07 12:21 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Add.java
> +            result = ((Number) simplerLeft).value + ((Number) simplerRight).value;
Чтобы не делать лишних кастов, подними версию JDK и используй pattern matching.
```
if (simplerLeft instanceof Number leftNumber && simplerRight instanceof Number rightNumber) {
            result = leftNumber.value + rightNumber.value;
```

2024-10-07 12:21 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Div.java
> +            result = ((Number) simplerLeft).value / ((Number) simplerRight).value;
Аналогично

2024-10-07 12:21 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Expression.java
> +    public abstract void printExpression();
Скорее всего везде одинаковая реализация

2024-10-07 12:21 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Main.java
> +    public static void main(String[] args) {
Не надо делать main, если он больше похож на тест. Сделай просто тест.

2024-10-07 12:21 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Mul.java
> +    final Expression right;
Видимость

2024-10-07 12:21 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Mul.java
> +            result = ((Number) simplerLeft).value * ((Number) simplerRight).value;
Аналогично

2024-10-07 12:21 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Parser.java
> +    }
Я думаю, с аналогичной семантикой что-то есть у `Character`

2024-10-07 12:21 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Parser.java
> +    public static int operationOrder(char operation) {
Это приоритет?

2024-10-07 12:21 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Parser.java
> +    public static ArrayList<String> polishNotation(String string) {
Я уже много раз говорила про использование реализаций в сигнатурах

2024-10-07 12:21 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Parser.java
> +import java.util.Stack;
Не надо использовать java.util.Stack, он старый. Используй стековую часть `java.util.Deque`.

2024-10-07 12:21 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Parser.java
> +    public static Map<String, Double> parseVar(String string) {
Что будет, если сюда прилетит невалидная строка?

2024-10-07 12:21 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Sub.java
> +            result = ((Number) simplerLeft).value - ((Number) simplerRight).value;
Аналогично

2024-10-07 12:21 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Sub.java
> +        } else if (simplerRight.convertToString().equals(simplerLeft.convertToString())) {
Определяй свой `equals` для выражений, не надо сравнивать строки.

2024-10-07 14:36 UTC, rottenfishh commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Parser.java
> +    public static int operationOrder(char operation) {
да

2024-10-08 08:18 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Div.java
> +            System.out.println("division by zero");
Пиши в System.err

2024-10-08 08:18 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Main.java
> +    public static void main(String[] args) {
Удаляй

2024-10-08 08:18 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Number.java
> +        return (num.value == this.value);
Лишние скобки

2024-10-08 08:18 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/kolodina/expressions/Parser.java
> +        } catch (Exception s) {
Не надо ловить Exception, надо ловить конкретное исключение

2024-10-15 06:59 UTC, shadrina approved these changes

2024-10-15 09:03 UTC, merged