Task_1_2_1
rottenfishh/OOP pull request #14
Opened 2024-10-10 17:52 UTC by rottenfishh

2024-10-22 08:20 UTC, shadrina reviewed
Доделывай

2024-10-22 08:20 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kolodina/graph/Edge.java
> +public class Edge<T> {
record

2024-10-22 08:20 UTC, shadrina commented on Task_1_2_1/src/test/java/ru/nsu/kolodina/graph/ReadFromFileTest.java
> +    String pathGraph3 = "src/test/resources/Graph3.txt";
1) Через ресурсы
2) `getResourceAsStream()`

2024-10-22 08:20 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kolodina/graph/FileReader.java
> +    public <T> void readFromFile(String pathName, Graph<T> graph, Function<String, T> parse) {
throws IOException

2024-10-22 08:20 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kolodina/graph/IncidenceMatrix.java
> +        }
`vertices.stream()...`

2024-10-22 08:20 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kolodina/graph/IncidenceMatrix.java
> +        }
.

2024-10-22 08:20 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kolodina/graph/Vertex.java
> +public class Vertex<T> {
record

2024-10-23 11:42 UTC, shadrina requested changes

2024-10-23 11:42 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kolodina/graph/AdjMatrix.java
> +        int idx = vertices.indexOf(v);
Тут же NPE может вылететь? Обработай чисто.

2024-10-23 11:42 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kolodina/graph/AdjMatrix.java
> +                .findAny().orElse(null);
Напрашивается метод `findVertex`

2024-10-23 11:42 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kolodina/graph/AdjMatrix.java
> +                .findAny().orElse(null);
Раз 6 встречается этот код

2024-10-23 11:42 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kolodina/graph/AdjMatrix.java
> +                .findAny().orElse(null);
Аж 10. Должна была возникнуть такая мысль при очередном прописывании одинакового заклинания.

2024-10-23 11:42 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kolodina/graph/AdjMatrix.java
> +        int idxTo = vertices.indexOf(to);
Стоп. А чем это отличается от `int idxFrom = vertices.indexOf(edge.vertexFrom())`?

2024-10-23 11:42 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kolodina/graph/FileReader.java
> +            System.out.println("An error occurred.");
System.err

2024-10-23 11:42 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kolodina/graph/TopoSort.java
> +                    System.out.println("Graph has cycle, no toposort is possible");
System.err

2024-10-23 11:42 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kolodina/graph/FileReader.java
> +        } catch (FileNotFoundException e) {
По-моему мы на паре обсудили, что здесь будет чище кидать IOException наружу.

2024-10-23 18:27 UTC, rottenfishh commented on Task_1_2_1/src/main/java/ru/nsu/kolodina/graph/AdjMatrix.java
> +        int idxTo = vertices.indexOf(to);
ничем, мне просто казалось что так в лоб не будет работать, а оно работает))

2024-10-23 18:27 UTC, rottenfishh commented on Task_1_2_1/src/main/java/ru/nsu/kolodina/graph/AdjMatrix.java
> +        int idxTo = vertices.indexOf(to);
поменяю везде

2024-10-29 08:16 UTC, shadrina approved these changes

2024-10-29 08:16 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kolodina/graph/AdjMatrix.java
> +        int idxTo = vertices.indexOf(to);*/
Можно удалить

2024-10-29 10:38 UTC, merged