Task_1_1
rottenfishh/OOP pull request #9
Opened 2024-09-06 11:02 UTC by rottenfishh

2024-09-10 08:00 UTC, shadrina requested changes
В названии задачи содержится: номер семестра, номер блока задач, номер задачи в этом блоке. Здесь `Task_1_1_1`.

2024-09-10 08:00 UTC, shadrina commented on Task_1_1/settings.gradle.kts
> +rootProject.name = "untitled"
За вот этой конфигурацией лучше следить. Аккуратно ставим логически подходящее имя, выбираем пакет в соответствии с доменом, в котором мы работаем: `ru.nsu.kolodina`.

2024-09-10 13:36 UTC, rottenfishh commented
график
![изображение](https://github.com/user-attachments/assets/e95d5b1d-69b7-446d-bf39-2a959bbc9f04)

2024-09-10 13:37 UTC, rottenfishh commented
![изображение](https://github.com/user-attachments/assets/ca327a61-dded-476b-986e-6ccdd6024921)
график

2024-09-10 13:39 UTC, rottenfishh commented
![изображение](https://github.com/user-attachments/assets/ad3a1ee5-a3a5-4fa9-be99-971cafb85516)
график

2024-09-16 11:22 UTC, shadrina requested changes
Картинку с асимптотикой я уже видела?

2024-09-16 11:22 UTC, shadrina commented on Task_1_1_1/settings.gradle.kts
> +rootProject.name = "ru.nsu.kolodina"
1) Здесь нужно название проекта, а не пакет.
2) Пакет должен совпадать везде и имя пакета само по себе должно совпадать с путем в файловой системе до этого пакета.

2024-09-16 12:37 UTC, rottenfishh commented on Task_1_1_1/settings.gradle.kts
> +rootProject.name = "ru.nsu.kolodina"
Здравствуйте! В каком смысле "уже видели" ? 
Я поменяю название, но вроде как вы же в прошлом ревью сказали его именно на это и поменять...

2024-09-16 17:28 UTC, shadrina commented on Task_1_1_1/settings.gradle.kts
> +rootProject.name = "ru.nsu.kolodina"
Картинку вижу, не заглянула в обсуждения. 
По поводу названий и имен пакетов подойди на паре, я объясню.

2024-09-18 07:35 UTC, shadrina approved these changes

2024-09-19 13:56 UTC, merged